site_name: ValidOcean
site_url: https://noc-msm.github.io/ValidOcean/

repo_url: https://github.com/NOC-MSM/ValidOcean
repo_name: ValidOcean
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/icons/ValidOcean_Logo.png
  favicon: assets/icons/favicon.ico
  icon:
    edit: material/pencil 
    view: material/eye
    repo: fontawesome/brands/git-alt
  font:
    text: Raleway
    code: IBM Plex Mono
  features:
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - toc.integrate
    - navigation.tabs
    - navigation.expand
    - navigation.footer
    - search.suggest
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: cyan
      accent: light blue
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: cyan
      accent: light blue

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.blocks.caption

nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Observations: observations.md
  - Customisation: customisation.md
  - Tutorial: 
    - Learn By Examples:
      - ex1_getting_started.ipynb
      - ex2_sst_validation_workflow.ipynb
      - ex3_sea_ice_validation_workflow.ipynb
      - ex4_ocean_observations.ipynb
  - Contributing: contributing.md

plugins:
  - search
  - glightbox
  - marimo
  - mkdocs-jupyter:
      include_source: True

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/NOC-MSM/ValidOcean
      name: GitHub

copyright: Copyright &copy; 2025 Ollie Tooth

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js